<?php

/**
 * ISO 3166-1 alpha-2 country codes with English display names.
 */
return [
    'AD' => 'Andorra',
    'AE' => 'United Arab Emirates',
    'AR' => 'Argentina',
    'AT' => 'Austria',
    'AU' => 'Australia',
    'BD' => 'Bangladesh',
    'BE' => 'Belgium',
    'BR' => 'Brazil',
    'CA' => 'Canada',
    'CH' => 'Switzerland',
    'CL' => 'Chile',
    'CN' => 'China',
    'CO' => 'Colombia',
    'CZ' => 'Czechia',
    'DE' => 'Germany',
    'DK' => 'Denmark',
    'EG' => 'Egypt',
    'ES' => 'Spain',
    'FI' => 'Finland',
    'FR' => 'France',
    'GB' => 'United Kingdom',
    'GR' => 'Greece',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'ID' => 'Indonesia',
    'IE' => 'Ireland',
    'IL' => 'Israel',
    'IN' => 'India',
    'IT' => 'Italy',
    'JP' => 'Japan',
    'KE' => 'Kenya',
    'KR' => 'South Korea',
    'MX' => 'Mexico',
    'MY' => 'Malaysia',
    'NG' => 'Nigeria',
    'NL' => 'Netherlands',
    'NO' => 'Norway',
    'NZ' => 'New Zealand',
    'PH' => 'Philippines',
    'PK' => 'Pakistan',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'SA' => 'Saudi Arabia',
    'SE' => 'Sweden',
    'SG' => 'Singapore',
    'TH' => 'Thailand',
    'TR' => 'Turkey',
    'TW' => 'Taiwan',
    'UA' => 'Ukraine',
    'US' => 'United States',
    'VN' => 'Vietnam',
    'ZA' => 'South Africa',
];
