import React, { useEffect, useState } from 'react';
import { invoiceApi, type Invoice } from '../api/invoices';
import StatusBadge from '../components/StatusBadge';
import Pagination from '../components/Pagination';

export default function Invoices() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [page, setPage] = useState(1);
  const [lastPage, setLastPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<number | null>(null);

  const fetch = async (p = page) => {
    setLoading(true);
    try {
      const res = await invoiceApi.list(p);
      setInvoices(res.data);
      setLastPage(res.last_page);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to load invoices');
    }
    setLoading(false);
  };

  const handleDelete = async (invoice: Invoice) => {
    if (!confirm(`Delete invoice ${invoice.invoice_number}?`)) return;
    setDeleting(invoice.id);
    setError(null);
    setSuccess(null);
    try {
      const res = await invoiceApi.delete(invoice.id);
      setSuccess(res.message);
      fetch();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to delete invoice');
    }
    setDeleting(null);
  };

  useEffect(() => { fetch(); }, [page]);

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Invoices</h1>
          <p className="mt-1 text-sm text-gray-500">
            Invoices are auto-generated by the CreateInvoiceWorkflow when an OrderCreated event is received
          </p>
        </div>
        <button onClick={() => fetch()} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">
          🔄 Refresh
        </button>
      </div>

      {success && (
        <div className="mb-4 rounded-lg bg-green-50 border border-green-200 p-4">
          <p className="text-sm text-green-700">✅ {success}</p>
        </div>
      )}
      {error && (
        <div className="mb-4 rounded-lg bg-red-50 border border-red-200 p-4">
          <p className="text-sm text-red-700">❌ {error}</p>
        </div>
      )}

      <div className="bg-white shadow rounded-lg overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Invoice #</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Order ID</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Amount</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">State</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Correlation ID</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Created</th>
              <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {loading ? (
              <tr><td colSpan={8} className="px-6 py-10 text-center text-sm text-gray-400">Loading...</td></tr>
            ) : invoices.length === 0 ? (
              <tr><td colSpan={8} className="px-6 py-10 text-center text-sm text-gray-400">No invoices yet. Create an order to trigger invoice generation.</td></tr>
            ) : (
              invoices.map((inv) => (
                <tr key={inv.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 text-sm font-medium text-gray-900">#{inv.id}</td>
                  <td className="px-6 py-4 text-sm font-mono text-gray-700">{inv.invoice_number}</td>
                  <td className="px-6 py-4 text-sm text-gray-700">{inv.order_id ? `#${inv.order_id}` : '—'}</td>
                  <td className="px-6 py-4 text-sm text-gray-700">${inv.amount}</td>
                  <td className="px-6 py-4">
                    <StatusBadge status={inv.state} />
                    {inv.state === 'failed' && inv.state_failure_description && (
                      <p className="text-xs text-red-500 mt-1 max-w-xs truncate">{inv.state_failure_description}</p>
                    )}
                  </td>
                  <td className="px-6 py-4 text-xs font-mono text-gray-500">{inv.correlation_id?.slice(0, 8)}…</td>
                  <td className="px-6 py-4 text-xs text-gray-400">{new Date(inv.created_at).toLocaleString()}</td>
                  <td className="px-6 py-4 text-right">
                    <button
                      onClick={() => handleDelete(inv)}
                      disabled={deleting === inv.id}
                      className="text-red-600 hover:text-red-900 text-sm font-medium disabled:opacity-50"
                    >
                      {deleting === inv.id ? 'Deleting…' : 'Delete'}
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
        <Pagination currentPage={page} lastPage={lastPage} onPageChange={setPage} />
      </div>
    </div>
  );
}
