filegroup(
    name = "ui_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "node_modules/**",
            "dist/**",
            ".env",
        ],
    ),
    visibility = ["//visibility:public"],
)

# Run the UI dev server
# Usage: bazelisk run //ui:run
sh_binary(
    name = "run",
    srcs = ["//scripts:run_service.sh"],
    args = ["ui"],
    data = [
        ":ui_files",
        "//:docker-compose.yml",
    ],
)
